name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.3.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'true'
          custom_labels: '{"feat": "type/feature", "fix": "type/bug", "docs": "area/docs", "test": "area/tests", "ci": "area/ci", "refactor": "type/refactor", "perf": "type/performance", "chore": "type/chore", "revert": "type/revert"}'
